services:
  - type: web
    name: flask-ultralytics-app
    env: python
    plan: free  # or 'starter' for paid plan
    region: oregon  # or your preferred region
    branch: main  # or 'master' based on your repo
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true  
